e_ggplot<-function(explaining=0){

if(explaining==0) {

cat("library(readxl); library(dplyr); library(ggplot2)  ", '\n')
cat("Adata <- read_excel('house20.xlsx')  ", '\n')
cat("  ", '\n')
cat("indexVariables<-c(3, 4, 6, 9, 277, 290, 304, 309, 310)  ", '\n')
cat("Adata<-Adata[ ,indexVariables]  ", '\n')
cat("colnames(Adata)<-c('가구주', 'age', 'type', 'occtype', 'nfamily', 'income','asset', 'debt', 'edu')  ", '\n')
cat("Adata<-Adata%>%filter(income!=9999999 & asset!=9999999 & debt!=9999999)  ", '\n')
cat("  ", '\n')
cat("# Adata$age값을 4개의 그룹으로 나눈다  ", '\n')
cat("cn<-quantile(Adata$age, c(.25, .5, .75))  ", '\n')
cat("  ", '\n')
cat("# age변수값을 4개의 그룹으로 나누는 데 각 경계값을 구한다.  ", '\n')
cat("Bdata<-mkgroup(Adata$age, cn)  ", '\n')
cat("#  Cutting Numbers : 1983 1998 2011  ", '\n')
cat("  ", '\n')
cat("Adata<-cbind(Adata, Bdata)  ", '\n')
cat("Adata<-Adata%>%rename(AGE_group = grouping)  ", '\n')
cat("tmp <- Adata %>% group_by(AGE_group) %>% summarize(부채평균=mean(debt), 자료수=n())  ", '\n')

invisible(readline(prompt="Press [enter] to continue"))

cat("ggplot(tmp, aes(x=AGE_group, y=부채평균))   ", '\n')
cat("+ geom_bar(stat='identity',fill='salmon3', col='black', width=.9)   ", '\n')
cat("+ theme(axis.text.x=element_text(color='black', size=11, angle=-40, vjust=-1))   ", '\n')
cat("+ theme(axis.text.y=element_text(color='black', size=11))   ", '\n')
cat("+ scale_x_discrete(limits=c('1983년이하', '1998년이하', '2011년이하','2011년이상'))   ", '\n')
cat("+ labs(x = '가구주가 된 연도', y = '부채 평균')  ", '\n')
cat("+ theme(axis.title=element_text(size=20, face='bold'))   ", '\n')
cat("+ geom_text(aes(label = round(부채평균, 0)), vjust = 1.4, angle=0)   ", '\n')
cat("+ ylim(0, 11000)   ", '\n')
cat("   ", '\n')
cat("ggplot(tmp, aes(x=AGE_group, y=부채평균))   ", '\n')
cat("+ geom_bar(stat='identity',fill='salmon3', col='black', width=.9)   ", '\n')
cat("+ theme(axis.text.x=element_text(color='black', size=11, angle=-40, vjust=-1))   ", '\n')
cat("+ theme(axis.text.y=element_text(color='black', size=11))   ", '\n')
cat("+ scale_x_discrete(limits=c('1983년이하', '1998년이하', '2011년이하','2011년이상'))   ", '\n')
cat("+ labs(x = '가구주가 된 연도', y = '부채 평균', title = '연령대별 부채평균')  ", '\n')
cat("+ theme(axis.title=element_text(size=20, face='bold'), title = element_text(size=25, face='bold'))   ", '\n')
cat("+ geom_text(aes(label = round(부채평균, 0)), vjust = 1.4, angle=0) + ylim(0, 11000)  ", '\n')

invisible(readline(prompt="Press [enter] to continue"))

cat("library(ggplot2) # 패키지 로딩 ", '\n')
cat("    ", '\n')
cat("# 데이터셋 준비하기  ", '\n')
cat("국가<-c('미국','중국','일본','독일','영국','인도','프랑스','이탈리아','캐나다','대한민국' )  ", '\n')
cat("국내총생산<-c(22.99, 17.73, 4.93, 4.22, 2.18, 3.17, 2.93, 2.99, 1.99, 1.81)  ", '\n')
cat("인구수<-c('3.39','14.25','1.23','0.83','0.67','14.28','0.64','0.58','0.38','0.51')  ", '\n')
cat("Adata<-as.data.frame(cbind(국가, 국내총생산, 인구수))  ", '\n')
cat("Adata$일인당국내총생산<-NA  ", '\n')
cat("index<-c(2:4) ", '\n')
cat("Adata[,index]<-lapply(Adata[,index], as.numeric)  ", '\n')
cat("Adata$일인당국내총생산<-Adata$국내총생산/Adata$인구수  ", '\n')
cat("  ", '\n')

invisible(readline(prompt="Press [enter] to continue"))

cat("# 막대그래프 그리기  ", '\n')
cat("# 국내총생산 규모가 큰 나라부터 배열  ", '\n')
cat("ggplot(Adata, aes(x=reorder(국가, -국내총생산), y=국내총생산))   ", '\n')
cat("+ geom_bar(stat='identity', fill='salmon')   ", '\n')
cat("+ ggtitle('직업과 소득') # 타이틀  ", '\n')
cat("+ theme(plot.title = element_text(color='blue', size=30, face='bold'))  ", '\n')
cat("+ xlab('국가') + ylab('국내총생산')  ", '\n')
cat("+ theme(axis.title.x = element_text(color='blue', size=30, face='bold')) # x축 타이틀  ", '\n')
cat("+ theme(axis.title.y = element_text(color='blue', size=30, face='bold')) # y축 타이틀  ", '\n')
cat("+ theme(axis.text.x=element_text(color='black', size=16, face='bold', angle=90)) # x축 눈금  ", '\n')
cat("+ theme(axis.text.y=element_text(color='black', size=16, face='bold')) # y축 눈금  ", '\n')
cat("  ", '\n')

invisible(readline(prompt="Press [enter] to continue"))

cat("# 데이터셋 만들기  ", '\n')
cat("V1<-c('전문적 리더십', '변혁적 리더십', '책임적 리더십', '관리적 리더십')  ", '\n')
cat("V2<-c(4.51, 4.35, 4.18, 3.68)  ", '\n')
cat("Adata<-as.data.frame(cbind(V1, V2))  ", '\n')
cat("Adata$V2<-as.numeric(Adata$V2)  ", '\n')
cat("  ", '\n')
cat("# ggplot명령문을 줄단위로 적었지만, 모두 붙여서 입력해야 에러가 발생하지 않음  ", '\n')
cat("ggplot ( Adata, aes(x=V1, y=V2) ) + geom_bar(stat='identity', fill='salmon3', width=0.7)  ", '\n')
cat("	+ ylim(0, 5)  ", '\n')
cat("	+ xlab('리더십 유형') + ylab('리더십 평균')  ", '\n')
cat("	+ theme(axis.text.x=element_text(angle=40, hjust=1, size=10))   ", '\n')
cat("	+ theme(axis.title.x = element_text(face='bold'))  ", '\n')
cat("	+ theme(axis.title.y = element_text(face='bold'))   ", '\n')
cat("	+ geom_text(aes(label = round(V2, 2)), vjust = -1.4, angle=0)   ", '\n')

invisible(readline(prompt="Press [enter] to continue"))

cat("# 4개의 그래프를 배열하기  ", '\n')
cat("library(gridExtra)  ", '\n')
cat("a<-ggplot(Adata, aes(x=국가, y=국내총생산)) + geom_bar(stat='identity', fill='salmon3', width=0.7)  ", '\n')
cat("b<-ggplot(Adata, aes(x=국가, y=인구수)) + geom_bar(stat='identity', fill='salmon3', width=0.7)  ", '\n')
cat("c<-ggplot(Adata, aes(x=국가, y=일인당국내총생산)) + geom_bar(stat='identity', fill='salmon3', width=0.7)  ", '\n')
cat("d<-ggplot(Adata, aes(x=국가, y=인구수)) + geom_bar(stat='identity', fill='salmon3', width=0.7) ", '\n')
cat("grid.arrange(a,b,c,d, nrow=1, ncol=4)    ", '\n')
cat("  ", '\n')

invisible(readline(prompt="Press [enter] to continue"))

cat("# 산포도 그리기  ", '\n')
cat("ggplot(Adata, aes(x=V1, y=V2))+geom_point(color='gray2',size=4)  ", '\n')
cat("+ geom_smooth()   ", '\n')
cat("+ xlab('전체')+ylab('담배꽁초')   ", '\n')
cat("+ theme(axis.title.x = element_text(color='blue', size=30, face='bold')) # x축 타이틀  ", '\n')
cat("+ theme(axis.title.y = element_text(color='blue', size=30, face='bold')) # y축 타이틀  ", '\n')
cat("+ theme(axis.text.x=element_text(color='red', size=16, face='bold', angle=90)) # x축 눈금  ", '\n')
cat("+ theme(axis.text.y=element_text(color='red', size=16, face='bold')) # y축 눈금  ", '\n')
cat("+ geom_text(aes(label = round(V2,2))) # 데이터값 표시  ", '\n')
cat("+ ggtitle('화재원인:담배꽁초') # 타이틀  ", '\n')
cat("+ theme(plot.title = element_text(color='red', size=30, face='bold')) # 타이틀 폰트조정  ", '\n')
}}